name: Release and publish
on:
  release:
    types: [released, prereleased]

jobs:
  build:
    name: Build the base artifact
    runs-on: ubuntu-latest
    if: github.event.release.draft == false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install composer dependencies
        run: composer install --no-dev -o

      - name: Bump version
        run: make version
        env:
          VERSION: ${{ github.event.release.tag_name }}

      - name: Create & upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}
          path: ./

  upload_release_asset:
    name: Upload the zip asset to the release
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.event.repository.name }}

      - name: Bundle the zip
        run: |
          cd ${{ github.event.repository.name }}
          make zip

      - name: Publish the zip
        uses: actions/upload-release-asset@v1<
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ github.event.repository.name }}/dist/${{ github.event.repository.name }}-${{ github.event.release.tag_name }}.zip
          asset_name: ${{ github.event.repository.name }}-${{ github.event.release.tag_name }}.zip
          asset_content_type: application/zip
